//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GoodsManageSystem.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_GOODSMANAGESYSTEM_DIALOG    102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_CLIENT               130
#define IDD_DIALOG_SELL                 131
#define IDD_DIALOG_BUY                  132
#define IDD_DIALOG_INPUT_CLIENT         133
#define IDD_DIALOG_INPUT_SELL           134
#define IDD_DIALOG_INPUT_BUY            135
#define IDR_MENU1                       137
#define IDR_MENUMAIN                    138
#define IDI_ICON1                       140
#define IDI_ICON2                       141
#define IDI_ICON3                       142
#define IDD_DIGPREVIEW                  143
#define IDD_DIALOG_BASEINFO             144
#define IDD_DIALOG_INPUT_BASEINFO       145
#define IDD_DIALOG_ADD_USER             146
#define IDD_DIALOG_LOGIN                148
#define IDD_DIALOG_MODIFY_PASSWD        149
#define IDD_DIALOG_DELETE_USER          150
#define IDD_DIALOG_SCHEDULE             151
#define IDD_DIALOG_POST                 152
#define IDD_DIALOG_LOGIN2               153
#define IDD_DIALOG_DETAIL               154
#define IDD_DIALOG_OUTPUT               155
#define IDD_DIALOG_MODIFY_PASSWD_ADMIN  156
#define IDD_DIALOG_MODIFY_PERMISSION    157
#define IDD_DIALOG_NEW_LIST             158
#define IDD_DIALOG_MODIFY_LIST1         159
#define IDD_DIALOG_LIST_QUERY           160
#define IDD_DIALOG_MAKEING              161
#define IDD_DIALOG_UNPOST               162
#define IDI_ICON8                       185
#define IDI_USER_ADD                    187
#define IDI_USER_MODIFY                 188
#define IDI_LIST_ADD                    189
#define IDI_MAKEING                     190
#define IDI_LIST_MODIFY                 191
#define IDI_USER_ADD1                   192
#define IDI_PERMISSION                  193
#define IDI_LIST                        194
#define IDI_LIST_ADD1                   195
#define IDI_LIST_QUERY                  196
#define IDI_USER_PASSWD                 197
#define IDI_PERMISSIONS                 198
#define IDI_LIST_QUERY1                 200
#define IDI_PERMISSION_MODIFY1          201
#define IDI_LIST_ADD2                   203
#define IDI_UNPOST                      204
#define IDI_POST                        205
#define IDI_USER_DEL1                   206
#define IDI_POST_UNPOST                 207
#define IDI_MAKEING1                    208
#define IDI_OUTPUT                      209
#define IDI_MAIN2                       210
#define IDI_DETAIL                      211
#define IDI_PROCESS                     212
#define IDI_ICON4                       214
#define IDB_BITMAP1                     217
#define IDC_TAB1                        1000
#define IDC_COMBO_CLIENT                1001
#define IDC_EDIT_CLIENT                 1002
#define IDC_BUTTON_CLIENT_SELECT        1003
#define IDC_BUTTON_CLIENT_ADD           1004
#define IDC_LIST_CLIENT                 1005
#define IDC_COMBO_SELL                  1006
#define IDC_EDIT_SELL                   1007
#define IDC_BUTTON_SELL_SELECT          1008
#define IDC_BUTTON_SELL_ADD             1009
#define IDC_LIST_SELL                   1010
#define IDC_COMBO_BUY                   1011
#define IDC_EDIT_BUY                    1012
#define IDC_BUTTON_BUY_SELECT           1013
#define IDC_BUTTON_BUY_ADD              1014
#define IDC_LIST_BUY                    1015
#define IDC_EDIT_COMPANYNAME            1016
#define IDC_EDIT_TAXINDEX               1017
#define IDC_EDIT_BANKNO                 1018
#define IDC_EDIT_ADDRESSPHONE           1019
#define IDC_EDIT_RECEIVER               1020
#define IDC_EDIT_MAILADDRESSPHONE       1021
#define IDC_EDIT_INPUTSELL_SELLPRICE    1023
#define IDC_EDIT_INPUTSELL_TOTALPRICE   1024
#define IDC_DATETIMEPICKER1             1025
#define IDC_EDIT_INPUTSELL_COMPANYNAME  1027
#define IDC_BUTTON_ADD                  1028
#define IDC_EDIT_INPUTSELL_PRODUCTMODEL 1029
#define IDC_EDIT_INPUTSELL_PRONUM       1030
#define IDC_EDIT_INPUTSELL_PROPRICE     1031
#define IDC_LIST_Product                1032
#define IDC_EDIT_INPUTBUY_SELLPRICE     1033
#define IDC_EDIT_CLIENT_LOGID           1033
#define IDC_EDIT_INPUTBUY_TOTALPRICE    1034
#define IDC_EDIT_SELL_LOGID             1034
#define IDC_DATETIMEPICKER2             1035
#define IDC_EDIT_BUY_LOGID              1036
#define IDC_EDIT_INPUTBUY_COMPANYNAME   1037
#define IDC_BUTPREVIEW                  1037
#define IDC_BUTTON_ADD2                 1038
#define IDC_BUTPRINT                    1038
#define IDC_EDIT_INPUTBUY_PRODUCTMODEL  1039
#define IDC_EDIT_INPUTSELL_USERADDRESS  1039
#define IDC_EDIT_INPUTBUY_PRONUM        1040
#define IDC_EDIT_INPUTSELL_USERPHONE    1040
#define IDC_EDIT_INPUTBUY_PROPRICE      1041
#define IDC_EDIT_INPUTSELL_USERNAME     1041
#define IDC_LIST_Product2               1042
#define IDC_EDIT_INPUTSELL_SELLNAME     1042
#define IDC_EDIT_INPUTSELL_SELLPHONE    1043
#define IDC_EDIT_INPUTSELL_UINT         1044
#define IDC_EDIT_INPUTSELL_MONEY        1045
#define IDC_EDIT_INPUTSELL_TIPS         1046
#define IDC_COMBO_BASEINFO              1047
#define IDC_EDIT_BASEINFO               1048
#define IDC_BUTTON_BASEINFO_ADD         1049
#define IDC_LIST_BASEINFO               1050
#define IDC_EDIT_LISTID                 1055
#define IDC_EDIT_CLIENTNAME             1056
#define IDC_EDIT_RECEIVE_NAME           1057
#define IDC_DATETIMEPICKER_RECEIVEDATE  1061
#define IDC_DATETIMEPICKER_ENDDATE      1062
#define IDC_EDIT_DEPARTMENT             1063
#define IDC_EDIT_ADDRESS                1064
#define IDC_EDIT_PHONE                  1065
#define IDC_EDIT_MONDY                  1066
#define IDC_EDIT_SIZE                   1067
#define IDC_EDIT_MATERIAL               1068
#define IDC_EDIT_COLOR                  1069
#define IDC_EDIT_PAINT                  1070
#define IDC_EDIT_BOTTOM                 1071
#define IDC_EDIT_ACCURACY               1072
#define IDC_EDIT_ERRORRANGE             1073
#define IDC_RICHEDIT_OTHER              1075
#define IDC_BUTTON_START_LIST           1076
#define IDC_BUTTON_END_LIST             1077
#define IDC_EDIT1_TOTELNUMBER           1078
#define IDC_BUTTON_SUBMITLIST           1079
#define IDC_BUTTON_EXCEL                1080
#define IDC_BUTTON_TC_POST              1081
#define IDC_BUTTON1                     1081
#define IDC_BUTTON_DELETE_USER          1082
#define IDC_EDIT_TECHNICAL_NUMBER       1083
#define IDC_BUTTON_MODIFY_PASSWD        1083
#define IDC_BUTTON_PD_POST              1084
#define IDC_EDIT_USER_NAME              1084
#define IDC_EDIT_PD_NUMBER              1085
#define IDC_COMBO_DEPARTMENT            1085
#define IDC_BUTTON_STORAGE_POST         1086
#define IDC_EDIT_PASSWD                 1086
#define IDC_EDIT_STORAGE_NUMBER         1087
#define IDC_EDIT_PASSWD2                1087
#define IDC_BUTTON_SEND_POST            1088
#define IDC_EDIT_USER                   1088
#define IDC_EDIT_SEND_NUMBER            1089
#define IDC_IPADDRESS1                  1091
#define IDC_EDIT_NEW_PASSWD             1094
#define IDC_EDIT_NEW_PASSWD2            1095
#define IDC_EDIT_POST_ID1               1097
#define IDC_EDIT_POST_NUM1              1098
#define IDC_EDIT_POST_ID2               1099
#define IDC_EDIT_POST_NUM2              1100
#define IDC_EDIT_POST_ID3               1101
#define IDC_EDIT_POST_NUM3              1102
#define IDC_EDIT_POST_ID4               1103
#define IDC_EDIT_POST_NUM4              1104
#define IDC_EDIT_POST_ID5               1105
#define IDC_EDIT_POST_NUM5              1106
#define IDC_BUTTON2                     1107
#define IDC_BUTTON_POST                 1108
#define IDC_BUTTON_SCHDEULE_SELECT      1109
#define IDC_COMBO_SCHEDULE              1110
#define IDC_LIST_SCHDEULE               1111
#define IDC_EDIT_DETAIL                 1116
#define IDC_BUTTON_DETAIL_SELECT        1117
#define IDC_LIST_DETAIL                 1118
#define IDC_COMBO2                      1119
#define IDC_TREE1                       1120
#define IDC_COMBO_OUTPUT                1121
#define IDC_LIST_OUTPUT                 1122
#define IDC_CHECK_SAVE_LIST             1123
#define IDC_CHECK_MODIFY_LIST_BEFORE    1124
#define IDC_CHECK_MODIFY_LIST_AFTER     1125
#define IDC_CHECK_QUERY_LIST            1126
#define IDC_CHECK_START_LIST            1127
#define IDC_CHECK_DEL_LIST              1128
#define IDC_CHECK_END_LIST              1129
#define IDC_CHECK_REFUND                1130
#define IDC_CHECK_POST_TC               1131
#define IDC_CHECK_POST_PD               1132
#define IDC_CHECK_POST_STORAGE          1133
#define IDC_CHECK_POST_SEND             1134
#define IDC_CHECK_PERMISSION            1136
#define IDC_EDIT_PEOPLE                 1138
#define IDC_CHECK_MODELING              1139
#define IDC_CHECK_DESIGN_SERVER         1140
#define IDC_CHECK_SCAN                  1141
#define IDC_CHECK_MODELING_PRINT        1142
#define IDC_CHECK_HAS_MODELING          1143
#define IDC_CHECK_NO_MODELING           1144
#define IDC_EDIT_TOTEL_NUMBER           1145
#define IDC_EDIT_SHINE                  1146
#define IDC_EDIT_BILL                   1148
#define IDC_EDIT_USAGE                  1149
#define IDC_EDIT_LISTTNAME              1150
#define IDC_EDIT_VOLUEME                1151
#define IDC_EDIT1_TRUE_NUMBER           1152
#define IDC_BUTTON_MODIFYLIST           1153
#define IDC_EDIT_QUERYLISTID            1154
#define IDC_EDIT_VOLUME_SENDID          1155
#define IDC_EDIT_VOLUME_SENDID2         1156
#define IDC_EDIT_VOLUME_SENDID3         1157
#define IDC_EDIT_VOLUME_SENDID4         1158
#define IDC_EDIT_VOLUME_SENDID5         1159
#define IDC_STATIC1                     1160
#define IDC_STATIC2                     1161
#define IDC_STATIC3                     1162
#define IDC_STATIC4                     1163
#define IDC_STATIC5                     1164
#define IDC_CHECK_QC                    1165
#define ID_MODIFY                       1167
#define IDC_STATIC_CONNECT              1168
#define IDC_EXCEL                       1169
#define ID_MENUITEM_INPUTSELL           32147
#define IDM_CLIENT_ADD                  32776
#define IDM_CLIENT_QUERY                32777
#define IDM_SELL_ADD                    32778
#define IDM_SELL_QUERY                  32779
#define IDM_BUY_ADD                     32780
#define IDM_BUY_QUERY                   32781
#define IDM_HELP                        32782

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        218
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         1170
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
